SELECT COUNT(*) FROM Employees;

SELECT * FROM Orders
LEFT JOIN Employees ON Orders.EmployeeID=Employees.EmployeeID;

SELECT * FROM Orders
LEFT JOIN OrderDetails ON Orders.OrderID=OrderDetails.OrderID
LEFT JOIN Products ON OrderDetails.ProductID=Products.ProductID;


SELECT (Price*Quantity) AS Revenue, * FROM (
    SELECT * FROM OrderDetails
             LEFT JOIN Orders ON OrderDetails.OrderID=Orders.OrderID
              ) AS ODFull
LEFT JOIN Products ON ODFull.ProductID=Products.ProductID;



SELECT (Quantity*Price),  FROM OrderDetails
LEFT JOIN Products ON OrderDetails.ProductID=Products.ProductID;


SELECT (Price*Quantity) AS Revenue, * FROM Orders, OrderDetails, Products
WHERE OrderDetails.ProductID=Products.ProductID
AND OrderDetails.OrderID=Orders.OrderID;

-- Returns revenue generated by each employee in order of most revenue
SELECT SUM(Price*Quantity) AS Revenue, EmployeeID FROM Orders, OrderDetails, Products
WHERE OrderDetails.ProductID=Products.ProductID
  AND OrderDetails.OrderID=Orders.OrderID
GROUP BY EmployeeID
ORDER BY SUM(Price*Quantity) DESC;

--  Which employee generated the most revenue?
SELECT TOP 1 SUM(Price*Quantity) AS Revenue, EmployeeID FROM Orders, OrderDetails, Products
WHERE OrderDetails.ProductID=Products.ProductID
  AND OrderDetails.OrderID=Orders.OrderID
GROUP BY EmployeeID
ORDER BY SUM(Price*Quantity) DESC;

--  Which employ generated the least revenue?
SELECT TOP 1 SUM(Price*Quantity) AS Revenue, EmployeeID FROM Orders, OrderDetails, Products
WHERE OrderDetails.ProductID=Products.ProductID
  AND OrderDetails.OrderID=Orders.OrderID
GROUP BY EmployeeID
ORDER BY SUM(Price*Quantity) ASC;

-- SELECT CONCAT(CAST(Employees.FirstName AS varchar), ' ', CAST(Employees.LastName AS varchar)) AS FullName, * FROM Employees;


SELECT SUM(Price*Quantity) AS Revenue, EmployeeID FROM Orders, OrderDetails, Products
WHERE OrderDetails.ProductID=Products.ProductID
  AND OrderDetails.OrderID=Orders.OrderID
GROUP BY EmployeeID
ORDER BY SUM(Price*Quantity) DESC;
